from models import Question

def get_questions():
    return [
        # ══════════════════════════════════════════════════════════════
        # EXISTING 22 QUESTIONS (recreated from seed.py)
        # ══════════════════════════════════════════════════════════════

        # --- Existing #1: Reading (diff 0.3) ---
        Question(skill_id="verbal_reading", question_type="reading", difficulty=0.3,
            passage_ar="Reading is one of the most important means by which humans acquire knowledge and culture. Studies have shown that regular reading improves mental abilities and develops critical thinking skills, as well as helps expand vocabulary and enhance expression ability.",
            text_ar="What is the main idea of the passage?",
            option_a="Reading is a waste of time",
            option_b="Reading is an important means of acquiring knowledge and developing abilities",
            option_c="Scientific studies are unreliable",
            option_d="Language expression does not improve with reading",
            correct_option="b",
            explanation_ar="Main idea: Reading is a means of acquiring knowledge and improving mental and expressive abilities.\nWhy other options are wrong:\n(a) Opposite of what the text says which describes reading positively.\n(c) The text cites studies as positive evidence.\n(d) The text confirms that reading expands vocabulary and enhances expression.",
            solution_steps_ar='["Identify passage topic: importance of reading","Extract mentioned benefits: knowledge, critical thinking, vocabulary, expression","Select option that combines these benefits → (b)"]',
            tags="main-idea", stage="diagnostic",
    rating_clarity=5, rating_cognitive=4, rating_fairness=5, rating_distractors=5, rating_difficulty_align=4, rating_explanation=5, rating_discrimination=4, rating_overall=4.57),

        # --- Existing #2: Pollution (diff 0.5) ---
        Question(skill_id="verbal_reading", question_type="reading", difficulty=0.5,
            passage_ar="Many major cities suffer from environmental pollution caused by industrial emissions and car exhaust. Some governments have taken strict measures to reduce this problem, including imposing taxes on polluting factories and encouraging the use of public transportation.",
            text_ar="It is understood from the passage that governments:",
            option_a="Ignore the pollution problem",
            option_b="Depend only on imposing taxes",
            option_c="Take multiple measures to combat pollution",
            option_d="Encourage the use of private cars",
            correct_option="c",
            explanation_ar="The text mentions two different measures: imposing taxes on factories and encouraging public transportation, meaning multiple measures.",
            solution_steps_ar='["Identify question: what governments do","Extract measures: taxes + encouraging public transport","Note multiplicity: two different measures → (c)"]',
            tags="inference", stage="diagnostic",
    rating_clarity=5, rating_cognitive=4, rating_fairness=5, rating_distractors=5, rating_difficulty_align=4, rating_explanation=5, rating_discrimination=4, rating_overall=4.57),

        # --- Existing #3: Sleep (diff 0.7) ---
        Question(skill_id="verbal_reading", question_type="reading", difficulty=0.7,
            passage_ar="Recent research has shown that adequate sleep plays a pivotal role in enhancing long-term memory. During deep sleep, the brain classifies information and transfers it from short-term to long-term memory. Therefore, continuous staying up late before exams may produce opposite results.",
            text_ar="It can be inferred from the passage that:",
            option_a="Staying up late before an exam improves performance",
            option_b="Deep sleep weakens memory",
            option_c="Studying at night is better than during the day",
            option_d="Lack of sleep may weaken the ability to remember information",
            correct_option="d",
            explanation_ar="Inference logic: Sleep enhances the transfer of information to long-term memory, and staying up late prevents this process, so lack of sleep weakens memory.",
            solution_steps_ar='["Understand role of sleep: transfer information to long-term memory","Understand effect of staying up: opposite results","Inference: lack of sleep → weakens memory → (d)"]',
            tags="inference", stage="diagnostic",
    rating_clarity=5, rating_cognitive=4, rating_fairness=5, rating_distractors=5, rating_difficulty_align=4, rating_explanation=5, rating_discrimination=5, rating_overall=4.71),

        # --- Existing #4: Technology (diff 0.2) ---
        Question(skill_id="verbal_reading", question_type="reading", difficulty=0.2,
            passage_ar="Technology has witnessed tremendous development in recent decades, as smartphones have become an integral part of our daily lives. These devices have enabled people to communicate instantly and access information anytime, anywhere.",
            text_ar="It is understood from the passage that smartphones have become important because of:",
            option_a="Their ability to replace computers in all office tasks",
            option_b="Providing instant communication and access to information anytime",
            option_c="Their low prices making them accessible to everyone",
            option_d="Developing social media applications exclusively",
            correct_option="b",
            explanation_ar="The text mentions two specific benefits of smartphones: instant communication and access to information.\nWhy other options are wrong:\n(a) The text does not mention replacing computers.\n(c) The text does not address prices.\n(d) The text mentions access to information as well, not just social media.",
            solution_steps_ar='["Identify question: reason for importance of smartphones","Extract reasons from text: instant communication + access to information","Check options: (b) combines both reasons mentioned in text → (b)"]',
            tags="main-idea", stage="diagnostic",
    rating_clarity=5, rating_cognitive=4, rating_fairness=5, rating_distractors=5, rating_difficulty_align=5, rating_explanation=5, rating_discrimination=4, rating_overall=4.71),

        # --- Existing #5: Sports (diff 0.2) ---
        Question(skill_id="verbal_reading", question_type="reading", difficulty=0.2,
            passage_ar="Sports are among the best means to maintain physical and mental health. Daily walking for thirty minutes reduces the risk of heart disease, improves mood, and relieves stress.",
            text_ar="It can be inferred from the passage that a person who does not exercise may be more susceptible to:",
            option_a="Heart disease and mood deterioration",
            option_b="Gaining high physical fitness over time",
            option_c="Automatic improvement in mental health",
            option_d="Increased ability to focus and produce",
            correct_option="a",
            explanation_ar="The text mentions that walking reduces the risk of heart disease and improves mood, so by reverse logic: not exercising increases the risk of heart disease and harms mood.\nWhy other options are wrong:\n(b) Opposite logic: without exercise, fitness does not improve.\n(c) The text links mental health improvement to exercise, not leaving it.\n(d) No basis in the text.",
            solution_steps_ar='["Understand benefits of exercise: reduce heart disease + improve mood","Apply reverse inference: no exercise = loss of these benefits","Answer: heart disease and mood deterioration → (a)"]',
            tags="detail", stage="diagnostic",
    rating_clarity=5, rating_cognitive=4, rating_fairness=5, rating_distractors=5, rating_difficulty_align=5, rating_explanation=5, rating_discrimination=4, rating_overall=4.71),

        # --- Existing #6: Poetry (diff 0.3) ---
        Question(skill_id="verbal_reading", question_type="reading", difficulty=0.3,
            passage_ar="Arabs have known poetry since the pre-Islamic era and considered it the diwan (register) of Arabs and a record of their conditions. The poet enjoyed a high status in his tribe, as he was its tongue expressing its glories and heroism.",
            text_ar="Why did the poet enjoy a high status in his tribe?",
            option_a="Because he was a military leader",
            option_b="Because he expressed the tribe's glories and heroism",
            option_c="Because he collected taxes",
            option_d="Because he judged between people",
            correct_option="b",
            explanation_ar="The text mentions that the poet was the tribe's tongue expressing its glories and heroism, which is the reason for his status.",
            solution_steps_ar='["Identify question: reason for poet's status","Search for evidence: its tongue expressing its glories and heroism","Select matching answer → (b)"]',
            tags="cause-effect", stage="foundation",
    rating_clarity=5, rating_cognitive=4, rating_fairness=5, rating_distractors=5, rating_difficulty_align=5, rating_explanation=5, rating_discrimination=4, rating_overall=4.71),

        # --- Existing #7: Energy (diff 0.3) ---
        Question(skill_id="verbal_reading", question_type="reading", difficulty=0.3,
            passage_ar="Many countries seek to develop renewable energy sources such as solar and wind energy. These efforts aim to reduce dependence on fossil fuels that contribute to environmental pollution and climate change.",
            text_ar="What is the goal of developing renewable energy sources?",
            option_a="Increase the use of fossil fuels",
            option_b="Reduce dependence on fossil fuels and protect the environment",
            option_c="Raise energy prices",
            option_d="Stop industrial development",
            correct_option="b",
            explanation_ar="The text explicitly states that the goal is to reduce dependence on fossil fuels that pollute the environment.",
            solution_steps_ar='["Identify question: goal of renewable energy","Extract answer: reduce dependence on fossil fuels","Connect cause to effect: fossil fuels pollute → alternative protects environment → (b)"]',
            tags="main-idea", stage="foundation",
    rating_clarity=5, rating_cognitive=4, rating_fairness=5, rating_distractors=5, rating_difficulty_align=4, rating_explanation=5, rating_discrimination=4, rating_overall=4.57),

        # --- Existing #8: Education (diff 0.5) ---
        Question(skill_id="verbal_reading", question_type="reading", difficulty=0.5,
            passage_ar="Studies have shown that early education contributes to developing social and cognitive skills in children. However, some experts warn against early academic pressure that may cause children to lose the joy of learning and cause psychological fatigue.",
            text_ar="What is the position of some experts on early education?",
            option_a="They reject it completely",
            option_b="They support it without reservation",
            option_c="They warn against early academic pressure on children",
            option_d="They see it as completely useless",
            correct_option="c",
            explanation_ar="The experts do not reject early education entirely, but they warn against a specific aspect which is academic pressure.",
            solution_steps_ar='["Identify question: experts' position","Extract position: warn against early academic pressure","Note precision: warning about pressure not rejecting education entirely → (c)"]',
            tags="main-idea", stage="foundation",
    rating_clarity=5, rating_cognitive=4, rating_fairness=5, rating_distractors=5, rating_difficulty_align=4, rating_explanation=5, rating_discrimination=4, rating_overall=4.57),

        # --- Existing #9: Economy (diff 0.5) ---
        Question(skill_id="verbal_reading", question_type="reading", difficulty=0.5,
            passage_ar="The global economy is witnessing a shift toward the digital economy, where e-commerce has come to represent an increasing percentage of trade volume. The COVID-19 pandemic contributed to accelerating this shift, as many consumers were forced to shop online.",
            text_ar="What was the effect of the COVID-19 pandemic on e-commerce according to the passage?",
            option_a="It led to the decline of e-commerce",
            option_b="It had no effect",
            option_c="It accelerated the shift toward e-commerce",
            option_d="It made people return to traditional stores",
            correct_option="c",
            explanation_ar="The text mentions that the pandemic contributed to accelerating this shift toward the digital economy.",
            solution_steps_ar='["Identify question: effect of COVID on e-commerce","Extract evidence: contributed to accelerating this shift","Select matching answer → (c)"]',
            tags="detail", stage="foundation",
    rating_clarity=5, rating_cognitive=4, rating_fairness=5, rating_distractors=5, rating_difficulty_align=4, rating_explanation=5, rating_discrimination=4, rating_overall=4.57),

        # --- Existing #10: Mars (diff 0.5) ---
        Question(skill_id="verbal_reading", question_type="reading", difficulty=0.5,
            passage_ar="Scientists have discovered that the planet Mars contained liquid water in the distant past. This discovery reinforces the hypothesis that primitive life may have existed on its surface during that era, opening new horizons for space exploration.",
            text_ar="What does the discovery of water on Mars mean according to the passage?",
            option_a="Certain current life on Mars",
            option_b="Impossibility of life on other planets",
            option_c="Possibility of previous primitive life and opening horizons for space exploration",
            option_d="That Mars is identical to Earth",
            correct_option="c",
            explanation_ar="The text says the discovery reinforces the hypothesis of primitive life (not confirmation), and opens new horizons.",
            solution_steps_ar='["Identify question: significance of water discovery","Note word hypothesis: meaning possibility not certainty","Connect result: open new exploration horizons → (c)"]',
            tags="detail", stage="foundation",
    rating_clarity=5, rating_cognitive=4, rating_fairness=5, rating_distractors=5, rating_difficulty_align=4, rating_explanation=5, rating_discrimination=4, rating_overall=4.57),
